name: Build and Deploy Backend Image

on:
  push:
    branches: [ main ]
    paths:
      - 'HMS/**'
      - '.github/workflows/backend-docker.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./HMS
          platforms: linux/amd64
          push: true
          tags: |
            ss272730/movie:latest
            ss272730/movie:v1.${{ github.run_number }}

      - name: Trigger Render deploy
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          if [ -n "$RENDER_DEPLOY_HOOK" ]; then
            curl -fsSL -X POST "$RENDER_DEPLOY_HOOK";
          else
            echo "RENDER_DEPLOY_HOOK secret not set; skipping Render deploy trigger";
          fi
